[workspace]
resolver = "2"
members = ["crates/router"]
default-members = ["crates/router"]

[workspace.package]
authors = ["迷渡 <justjavac@gmail.com>"]
homepage = "https://github.com/justjavac/gpui-router"
repository = "https://github.com/justjavac/gpui-router"
license = "MIT"
edition = "2024"
readme = "README.md"

[workspace.dependencies]
criterion = "0.5.1"
hashbrown = "0.15.2"
gpui = { git = "https://github.com/zed-industries/zed.git" }
smallvec = "1.14.0"
